# Generated by Django 5.2.5 on 2025-08-28 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bookID', models.AutoField(primary_key=True, serialize=False)),
                ('bookTitle', models.CharField(max_length=200)),
                ('bookAuthor', models.CharField(max_length=200)),
                ('bookGenre', models.CharField(blank=True, choices=[('fiction', 'Fiction'), ('nonfiction', 'Non-Fiction'), ('mystery', 'Mystery'), ('scifi', 'Sci-Fi'), ('fantasy', 'Fantasy')], max_length=20)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
