# Generated by Django 5.2.5 on 2025-08-29 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silentlibrary_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bookGenre',
            field=models.CharField(blank=True, choices=[('drama', 'Drama'), ('thriller', 'Thriller'), ('horror', 'Horror'), ('comedy', 'Comedy'), ('documentary', 'Documentary')], max_length=20),
        ),
    ]
