# Generated by Django 5.2.5 on 2025-09-02 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silentlibrary_app', '0003_book_cover_profile_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField(blank=True)),
            ],
        ),
    ]
